### ISSUE TITLE
Specimen Label Checklist

### ISSUE THREAD

**Issue by sylviakinosian** [sylviakinosian/spindle#2]
- [ ] Family
- [ ] Genus
- [ ] Species (include authorities at the lowest taxon rank)
- [ ] Locality
     - [ ] description of site
     - [ ] lat/long
     - [ ] elevation
     - [ ] country
     - [ ] state/province 
     - [ ] county (most detailed information you can give)
- [ ] Ecology (soil type, moisture, habitat, canopy cover, etc.)
- [ ] Associated species (use scientific names only)
- [ ] description of plant
- [ ] host/substrate
- [ ] other info / notes
- [ ] voucher info (study title, GENBANK #, etc)
- [ ] collector information
     - [ ] collector name
     - [ ] anyone with the collector
     - [ ] field ID / collection #1 
     - [ ] date collected
